// Generated by https://quicktype.io

export interface Fines {
    id: number;
    created_at: Date;
    username: string;
    team_name: string;
    fine: number;
    currency: string;
    fine_description: string;
    league_id: number;
    user_id: number;

}
